### ISSUE TITLE
Environment dimensions and plotting trajectories

### ISSUE THREAD

**Issue by njpzn** [bilalkabas/DRL-Nav#3]
1.I ran your code to understand that the size of each room in the airsim environment is 3.7 * 3.7 * 3.7, the mezzanine channel mouth between rooms rh=0.55, and in env_config.yml, offset represents x coordinates, some are 20, 32 I can't understand.
2.I want to know how to draw trajectories of the agent trained using depth and stacked gray images?
![image](https://user-images.githubusercontent.com/103270475/230815170-d84a2fcc-37cc-41b0-85dc-d25ba919ea68.png)
Sorry to bother you, can you give me some help. My mail is njpzn1@126.com.

**Comment by bilalkabas** [comment]
Hi,

**Answer 1:**
Dimensions of the rooms:
<img src="https://user-images.githubusercontent.com/53112883/232327582-e4cbe65f-8565-49d0-9c31-c5475cc5ac91.jpeg" width="400" />

With respect to the drone's movement, +x is the forward direction, the y-axis indicates the left-right direction, and the z-axis indicates the height. So, in the config file, the target indicates the y and z positions of the holes, and the offset indicates the x position. These positions are global meaning that they are not bounded by a single room, instead, they are with respect to the whole corridor environment. That's why offset increases gradually as the holes propagate through the corridor.

https://github.com/bilalkabas/DRL-Nav/blob/764159d2d6c4418b485e2c3db45c3044f41d618d/scripts/env_config.yml#L1-L7

**Answer 2:**
You should modify `airsim_env.py` to save the drone's x, y, and z positions into a `csv` file. Below, I put the link to the related code lines. You should save each trajectory into a separate file.

https://github.com/bilalkabas/DRL-Nav/blob/764159d2d6c4418b485e2c3db45c3044f41d618d/scripts/airsim_env.py#L239-L243

Note that you should run the `inference.py` in sequential mode by modifying `config.yml` by setting `test_type: "sequential"`.

I wrote the below MATLAB script to plot trajectories:

```
root = "trajectories/depth_hard/";
files = dir(root+"*.csv");

figure('Renderer', 'painters', 'Position', [500 500 600/1 170/1])

% Trajectory color
col = [199 43 16 20]./255;

x = 0;
for i=1:length(files)
    pose = readmatrix(root+files(i).name)';
    x = x + pose(end,1);
    plot(pose(:,1),pose(:,2), "linewidth", 2, Color=col)
    hold on
end

% Draw walls
wall_color = [158 158 158 1]./255;
wall_thick = 2;
for i=1:15
    xline(4*i,"linewidth", wall_thick, Color=wall_color)
end

% x,y coordinates of hole centers
centers = ...
    [[4400,150];...
    [4800,-150];...
    [5200,100];...
    [5600,-100];...
    [6000,100]]/100;

% Draw holes
viscircles(centers,ones(length(centers),1)*1.1,Color="#c79010",LineStyle=":")

xlabel("x [m]")
ylabel("y [m]")
grid on
axis equal
xlim([0 20.5]+(start-1)*20)
ylim([-5.5/2 5.5/2])
```

Below, I attach the plotting script and example trajectories so that you can reproduce the same plot.

[plot_trajectory.zip](https://github.com/bilalkabas/DRL-Nav/files/11242754/plot_trajectory.zip)

**Comment by njpzn** [comment]
Your answer helped me a lot, and your avatar is really handsome.

**Comment by njpzn** [comment]
Recently, I encountered some problems when building the UE4 environment, I want to ask you: 1 I added a point light and only built the light, but it was still black in the Scene = 0, my  settings.json   "SubWindows": [
    {
      "WindowID": 0,
      "ImageType": 2,
      "CameraName": "2",
      "Visible": true
    },
    {
      "WindowID": 1,
      "ImageType": 3,
      "CameraName": "3",
      "Visible": true
    },
    {
      "WindowID": 2,
      "ImageType": 0,
      "CameraName": "4",
      "Visible": true
    }
  ]
![image](https://github.com/bilalkabas/DRL-Nav/assets/103270475/f1054297-a4fc-406e-947c-79b84c96a41e)
2. I packaged the environment, and when I selected Airsim for the game mode, the map was also a map I built, but I found that there was an error when opening the exe file Plugin 'AirSim' failed to load because module 'AirSim' could not be found. Please ensure the plugin is properly installed, otherwise consider disabling the plugin for this project.
3. I use client.moveToZAsync(-1, 1).join() , but x, y, z = client.simGetVehiclePose(). position
print(x,y,z) prints a state of 0,0,-0.6166 with an error of nearly 0.3834, I'm not sure why, I want to use this value for the reward function calculation.And how to adjust the size of the drone, I used to compile the latest airism ,ue4=4.27.2, I feel that yours is twice as small as mine, and my hole has to be set very large
![V7C@XLN4YQD8YQLOV 6@AGF](https://github.com/bilalkabas/DRL-Nav/assets/103270475/29d498fe-9f10-4d6d-aa98-32fb3f6a35b4)
![TV$47P{_2RVOI(~O{H%@20Z](https://github.com/bilalkabas/DRL-Nav/assets/103270475/77e2876b-b358-41e3-ba02-33aa1ff7516b)

Thank you so much!It's too difficult to study alone.
